/** @type {import('tailwindcss').Config} */
export default {
  darkMode: false,
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
        },
        app: {
          bg: 'var(--app-bg)',
          surface: 'var(--app-surface)',
          'surface-secondary': 'var(--app-surface-secondary)',
          sidebar: 'var(--app-sidebar)',
          primary: 'var(--app-primary)',
          'primary-hover': 'var(--app-primary-hover)',
          secondary: 'var(--app-secondary)',
          accent: 'var(--app-accent)',
          success: 'var(--app-success)',
          warning: 'var(--app-warning)',
          danger: 'var(--app-danger)',
          'text-primary': 'var(--app-text-primary)',
          'text-secondary': 'var(--app-text-secondary)',
          border: 'var(--app-border)',
        },
      },
    },
  },
  plugins: [],
}
