import {
  Layers, UserCog, LogIn, DatabaseZap, CreditCard, Users, DollarSign,
  Calendar, GraduationCap, Car, Files, BarChart3, Bell,
  Network, ServerCog, Bug, Download, Printer, Settings, Tag, ShieldAlert
} from 'lucide-react'

// Enterprise Audit Logs navigation + page configuration.
// Each category renders through the generic AuditCategory page unless it has
// a dedicated `component` route (handled in App.jsx): user-activity, login-history, audit-settings.
export const auditCategories = [
  {
    id: 'all',
    name: 'All Logs',
    icon: Layers,
    description: 'Every action performed across the system with full filtering.',
    filters: {},
    tracked: ['User', 'Role', 'Module', 'Action', 'Date', 'Status', 'IP Address'],
  },
  {
    id: 'user-activity',
    name: 'User Activity',
    icon: UserCog,
    description: 'Complete activity history for a selected user.',
    special: 'user-activity',
    tracked: ['Timeline', 'Pages', 'CRUD', 'Reports', 'Documents', 'Searches', 'Exports', 'Prints', 'Sessions'],
  },
  {
    id: 'login-history',
    name: 'Login History',
    icon: LogIn,
    description: 'Login/logout records with device, location and session details.',
    special: 'login-history',
    tracked: ['Login', 'Logout', 'Session', 'Browser', 'Device', 'OS', 'IP', 'Location', 'Failed Logins', 'MFA'],
  },
  {
    id: 'crud-history',
    name: 'CRUD History',
    icon: DatabaseZap,
    description: 'Create, Read, Update, Delete, Restore, Approve, Reject, Print, Export and View actions.',
    filters: { actions: 'POST,PUT,PATCH,DELETE,GET' },
    tracked: ['Create', 'Read', 'Update', 'Delete', 'Restore', 'Approve', 'Reject', 'Print', 'Export', 'View'],
  },
  {
    id: 'license',
    name: 'License Activities',
    icon: CreditCard,
    description: 'Applications, approvals, renewals, suspensions, printing and more.',
    filters: { tables: 'licenses' },
    tracked: ['Applications', 'Approvals', 'Rejections', 'Renewals', 'Suspensions', 'Revocations', 'Printing', 'Replacements', 'Expirations'],
  },
  {
    id: 'driver',
    name: 'Driver Activities',
    icon: Users,
    description: 'Registration, profile updates, document verification and more.',
    filters: { tables: 'drivers' },
    tracked: ['Registration', 'Profile Updates', 'Address Changes', 'Photo Updates', 'Medical Updates', 'Document Verification'],
  },
  {
    id: 'payment',
    name: 'Payment Activities',
    icon: DollarSign,
    description: 'Payment creation, receipts, refunds, verification and cancellation.',
    filters: { tables: 'payments' },
    tracked: ['Creation', 'Receipt Printing', 'Refunds', 'Updates', 'Cancellation', 'Verification'],
  },
  {
    id: 'appointment',
    name: 'Appointment Activities',
    icon: Calendar,
    description: 'Booking, rescheduling, cancellation, completion and no-shows.',
    filters: { tables: 'appointments' },
    tracked: ['Booking', 'Rescheduling', 'Cancellation', 'Completion', 'No Show'],
  },
  {
    id: 'examination',
    name: 'Examination Activities',
    icon: GraduationCap,
    description: 'Theory/practical exams, examiner assignment, results and score changes.',
    filters: { tables: 'exams' },
    tracked: ['Theory', 'Practical', 'Examiner Assignment', 'Results', 'Pass', 'Fail', 'Score Changes'],
  },
  {
    id: 'vehicle',
    name: 'Vehicle Activities',
    icon: Car,
    description: 'Vehicle registration, ownership changes, inspection and updates.',
    filters: { tables: 'vehicles' },
    tracked: ['Registration', 'Ownership Changes', 'Inspection', 'Updates', 'Deletion'],
  },
  {
    id: 'document',
    name: 'Document Activities',
    icon: Files,
    description: 'Upload, download, print, delete, restore, replace and view.',
    filters: { tables: 'documents' },
    tracked: ['Upload', 'Download', 'Print', 'Delete', 'Restore', 'Replace', 'View'],
  },
  {
    id: 'report',
    name: 'Report Activities',
    icon: BarChart3,
    description: 'Report generation and export to PDF, Excel, CSV plus scheduling.',
    filters: { module: 'reports' },
    tracked: ['Generation', 'PDF Export', 'Excel Export', 'CSV Export', 'Print', 'Scheduled'],
  },
  {
    id: 'notification',
    name: 'Notification History',
    icon: Bell,
    description: 'Email, SMS, push and in-app notifications with delivery status.',
    filters: { tables: 'notifications' },
    tracked: ['Email', 'SMS', 'Push', 'In-App', 'Delivery Status'],
  },
  {
    id: 'api',
    name: 'API Activity',
    icon: Network,
    description: 'Endpoint, HTTP method, request/response time, status code and IP.',
    filters: {},
    columns: 'api',
    tracked: ['Endpoint', 'Method', 'Request Time', 'Response Time', 'Status Code', 'User', 'IP'],
  },
  {
    id: 'system',
    name: 'System Events',
    icon: ServerCog,
    description: 'Backups, scheduled jobs, restarts, config changes and maintenance.',
    filters: { module: 'system' },
    tracked: ['Database Backup', 'Scheduled Jobs', 'Server Restart', 'Config Changes', 'Cache Clear', 'Service Status', 'Maintenance Mode'],
  },
  {
    id: 'error',
    name: 'Error Logs',
    icon: Bug,
    description: 'Validation, database, API, server errors and application exceptions.',
    filters: { status: 'failed' },
    tracked: ['Validation Errors', 'Database Errors', 'API Errors', 'Server Errors', 'Exceptions', 'Stack Trace'],
  },
  {
    id: 'export',
    name: 'Data Export History',
    icon: Download,
    description: 'PDF, Excel, CSV, Word and JSON exports with file size and author.',
    filters: {},
    tracked: ['PDF', 'Excel', 'CSV', 'Word', 'JSON', 'Exported By', 'Export Time', 'File Size'],
  },
  {
    id: 'print',
    name: 'Print History',
    icon: Printer,
    description: 'Documents, receipts and licenses printed with copies and printer.',
    filters: {},
    tracked: ['Document', 'Receipt', 'License', 'Copies', 'Printer', 'Printed By', 'Date & Time'],
  },
  {
    id: 'settings',
    name: 'Audit Settings',
    icon: Settings,
    description: 'Configure retention, cleanup, archiving, permissions and integrity.',
    special: 'audit-settings',
    tracked: ['Retention', 'Cleanup', 'Archiving', 'Permissions', 'Security', 'Integrity', 'Storage'],
  },
  {
    id: 'service-pricing',
    name: 'Service Pricing',
    icon: Tag,
    description: 'Service creation, price changes, activation, deactivation and history.',
    filters: { tables: 'services' },
    tracked: ['Service Creation', 'Price Changes', 'Activation', 'Deactivation', 'Effective Dates', 'Reason', 'Changed By'],
  },
  {
    id: 'security',
    name: 'Security Events',
    icon: ShieldAlert,
    description: 'Unauthorized access attempts, permission changes, role modifications and breaches.',
    filters: { module: 'security' },
    tracked: ['Unauthorized Access', 'Permission Changes', 'Role Modifications', 'Password Changes', 'MFA Events', 'Security Breaches', 'Account Lockouts'],
  },
]

export const getAuditCategory = (id) => auditCategories.find((c) => c.id === id) || null
